eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /test/**
      serviceId: service-test
      stripPrefix: false
    api-b:
      path: /request/**
      serviceId: service-request
      stripPrefix: false