eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
server:
  port: 8500
  context-path: /request
spring:
  application:
    name: service-request
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
    percentage: 1.0

  #thymeleaf start
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    content-type: text/html
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  #thymeleaf end

  datasource:
      url: jdbc:mysql://localhost:3306/dby?useUnicode=true&characterEncoding=utf8
      username: root
      password: dby1234
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.dby.request.entity
  mapperLocations: classpath:mapper/*.xml
