eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

server:
  port: 8501
  context-path: /test

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dby?useUnicode=true&characterEncoding=utf8
    username: root
    password: dby1234
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: service-test
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
    percentage: 1.0

mybatis:
  type-aliases-package: com.dby.test.entity
  mapperLocations: classpath:mapper/*.xml
